# Generated by Django 3.2.5 on 2021-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0002_auto_20210713_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_major2',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_major3',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
