# Generated by Django 3.1.6 on 2021-07-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0007_auto_20210721_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='url',
        ),
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
