# Generated by Django 3.1.6 on 2021-07-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0008_auto_20210721_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachments',
            field=models.URLField(null=True),
        ),
    ]
