# Generated by Django 3.2.5 on 2021-07-25 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postbox', '0009_notice_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='read',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='store',
        ),
        migrations.CreateModel(
            name='UserNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postbox.notice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
