# Generated by Django 3.1.6 on 2021-07-25 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0010_auto_20210725_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 14, 26, 15, 623156, tzinfo=utc)),
        ),
    ]
