# Generated by Django 3.1.6 on 2021-08-02 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0011_notice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.AddField(
            model_name='notice',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 2, 14, 18, 29, 548370, tzinfo=utc)),
        ),
    ]
